local ls = require 'luasnip'
local s = ls.snippet

return {
  s('cft', {
    t {
      '#include <bits/stdc++.h>',
      'using namespace std;',
      'using ll = long long;',
      'using vi = vector<int>;',
      'using vl = vector<ll>;',
      '#define debug(x) cerr << #x << R"(: )" << x << \'\\n\';',
      '#define REP(i,a) for (int i = 0; i < a; ++i)',
      '#define FILL(a) for (auto &A : a) cin >> A;',
      '#define rall(x) (x).rbegin(), (x).rend()',
      '#define all(x) x.begin(), x.end()',
      '#define pb push_back',
      '#define ins insert',
      '#define fi first',
      '#define se second',
      'int test_n;',
      '',
      'void solve() {',
      '    ',
    },
    i(0),
    t {
      '',
      '}',
      '',
      'signed main() {',
      '    // ios::sync_with_stdio(false); cin.tie(nullptr);',
      '    int t; cin >> t;',
      '    while(t--) {',
      '        test_n++;',
      '        solve();',
      '    }',
      '}',
    },
  }),
  s('cf', {
    t {
      '#include <bits/stdc++.h>',
      'using namespace std;',
      'using ll = long long;',
      'using vi = vector<int>;',
      'using vl = vector<ll>;',
      '#define debug(x) cerr << #x << R"(: )" << x << \'\\n\';',
      '#define REP(i,a) for (int i = 0; i < a; ++i)',
      '#define FILL(a) for (auto &A : a) cin >> A;',
      '#define rall(x) (x).rbegin(), (x).rend()',
      '#define all(x) x.begin(), x.end()',
      '#define pb push_back',
      '#define ins insert',
      '#define fi first',
      '#define se second',
      '',
      'void solve() {',
      '    ',
    },
    i(0),
    t {
      '',
      '}',
      '',
      'signed main() {',
      '    // ios::sync_with_stdio(false); cin.tie(nullptr);',
      '    solve();',
      '}',
    },
  }),
}
